version: '3'
services:
  php:
    container_name: php-container
    build: ./
    ports:
      - ${SIMON_APACHE_PORT}:80
    volumes:
      - ./php-code:/var/www/html/
    links:
      - mysql:mysqldb

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${SIMON_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SIMON_MYSQL_DATABASE}
      MYSQL_USER: ${SIMON_MYSQL_USER}
      MYSQL_PASSWORD: ${SIMON_MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/simon.sql  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - ${SIMON_PMA_PORT}:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
